### ISSUE TITLE
docker in Jenkins build

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt-client#10]
According to the last jenkins [build log ](https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-mqtt-client/9/consoleText) - it fails and docker is the cause.

I think the reason is that docker requires the root access. 

Another consideration is that docker is not installed on CI server :)

Any suggestions/observations?

**Comment by ppatierno** [comment]
@vietj said me that we cannot have docker in Cloudbees.

As he said, Docker is more handy for doing local development but we can use a maven profile that is active on Cloudbees for testing via the Eclipse hosted server using system properties. 
So using the eclipse MQTT online broker when the build happens on Jenkins.

Is this your thought ? right @vietj ?

**Comment by vietj** [comment]
yes, that's what we do for a couple of projects, we can also download a binary and run it using shell script in the jenkins config. Docker is good for testing on mac for instance

**Comment by ppatierno** [comment]
@vietj can you point me out to this projects ? I'd like to take a look. Thanks !

**Comment by pmlopes** [comment]
We also experimented with Travis to solve the lack of docker in a couple of repos, maybe that can also help you?

**Comment by ppatierno** [comment]
@pmlopes but in this case who generates the artifacts for Maven , Jenkins or Travis ? Or are you saying that there are some projects where we don't use Jenkins but only Travis ? Of course it can help can you give me more info ? Thanks !

**Comment by pmlopes** [comment]
@ppatierno there a couple of projects on travis, the most docker centric one is `vertx-grpc-java-compiler` here: https://travis-ci.org/vert-x3/vertx-grpc-java-compiler

Since we need to have several cross compilers for all OSes (Windows, Linux, MacOS) and docker was not available on Jenkins everything is then run on travis.

Other modules have been experimenting with it too:

* https://travis-ci.org/vert-x3/vertx-mysql-postgresql-client
* https://travis-ci.org/vert-x3/vertx-sql-common
